apiVersion: v1
kind: Service
metadata:
  name: node-mongo-page-hit
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30800
      targetPort: 8000
  selector:
    name: node-mongo-page-hit