apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-page-hit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mongo-page-hit
  template:
    metadata:
      labels:
        app: node-mongo-page-hit
    spec:
      containers:
      - name: node-mongo-page-hit
        image: hegde9/node-mongo-page-hit:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: '8000'